version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    post_install:
        - python -m pip install --no-cache-dir -r docs/requirements.txt

# Build PDF
formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: python
  system_packages: true
